language: go
go_import_path: github.com/worktimeassistant/gin-limit
go:
  - 1.7
  - 1.8

install:
  - go get github.com/Masterminds/glide
  - glide install
  - go install github.com/ory-am/hydra

script:
  - go test -race $(glide nv)
